export {default as App} from "./App"
export * from "./main"
export * from "./components/molecule/Detail"
//// export * from "./components/molecule/HamburgerMenu"
export * from "./components/molecule/InfoCharacter"
export * from "./components/organism/Header"
export * from "./components/molecule/SplashArt"
export * from "./data/infoCharacters"
export * from "./data/infoDetailHome"
export * from "./data/infoSplashArtHome"
export * from "./data/infoNavegation"
