version: "3.9"

services:
  bd-postgresql:
    image: postgres:latest
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
    - "${POSTGRES_PORT}:5432"
    restart: unless-stopped

volumes:
  postgres_data:
